"""隐藏 AI 署名：真实的执行链路，不是一个没人读的开关（需求 8）。

参考实现的「隐藏 AI 署名」把 commit / PR 的署名尾注置空，
作用对象是编码客户端写 git commit 时的 `Co-Authored-By`。本项目不代写 commit，
但**同一个用户意图**在聊天场景里有确切的落点：模型经常在回复里自报身份
（「作为一个 AI 助手，我……」「本回复由 AI 生成」），QQ / 企业微信这类面向真人的
渠道里这类句子既占篇幅又暴露实现细节。

因此按语义实现：供应商级开关，打开后在**该供应商返回的回复文本**上移除
AI 自我署名句，且只移除署名本身，不动答案。

三条边界，每条都有对应用例：

1. **默认关闭，关闭时一个字符都不改。** 这是一个会改写模型输出的开关，
   默认改写等于替用户做决定。
2. **只删句子，不删答案。** 「作为一个 AI，我建议你先备份」里，
   「我建议你先备份」是答案，必须留下。
3. **不碰代码块。** 代码里出现 `AI` 字样是内容而不是署名；
   在代码里做替换会改坏用户要执行的东西。
"""

from __future__ import annotations

import pytest

from kirara_ai.llm.attribution import strip_ai_attribution


def test_disabled_by_default_leaves_text_untouched():
    """这条是最重要的：开关关闭时必须逐字符不变。"""
    text = "作为一个 AI 助手，我建议你先备份。"

    assert strip_ai_attribution(text, enabled=False) == text


@pytest.mark.parametrize(
    "text",
    [
        "本回复由 AI 生成。",
        "以上内容由人工智能生成，仅供参考。",
        "我是一个AI语言模型。",
        "This response was generated by an AI assistant.",
        "I am an AI language model.",
    ],
)
def test_removes_standalone_attribution_sentences(text: str):
    """整句都是署名/免责声明时，整句删掉。"""
    assert strip_ai_attribution(text, enabled=True).strip() == ""


@pytest.mark.parametrize(
    ("text", "kept"),
    [
        ("作为一名 AI 助手，我无法访问实时数据。", "我无法访问实时数据。"),
        ("As an AI language model, I cannot browse the web.", "I cannot browse the web."),
    ],
)
def test_prefix_forms_keep_the_statement_that_follows(text: str, kept: str):
    """这些是**前缀**形态，不是整句署名。

    「作为一名 AI 助手，我无法访问实时数据」里，「我无法访问实时数据」是对
    「你能查实时数据吗」的回答，删掉它等于把答案连同署名一起丢了。
    署名与答案的分界就在那个逗号上。
    """
    result = strip_ai_attribution(text, enabled=True)

    assert result == kept
    assert "AI" not in result and "ai " not in result.lower()


def test_keeps_the_answer_when_attribution_is_only_a_prefix():
    """署名只是前缀时，答案必须保留。

    「作为一个 AI，我建议你先备份」删掉整句就把答案一起删了——
    那不是「隐藏署名」，那是丢答案。
    """
    result = strip_ai_attribution(
        "作为一个 AI 助手，我建议你先备份数据库。", enabled=True
    )

    assert "我建议你先备份数据库" in result
    assert "AI 助手" not in result


def test_keeps_surrounding_content():
    source = "先说结论：可以升级。\n\n本回复由 AI 生成。\n\n升级前请先备份。"

    result = strip_ai_attribution(source, enabled=True)

    assert "先说结论：可以升级。" in result
    assert "升级前请先备份。" in result
    assert "由 AI 生成" not in result


def test_never_rewrites_inside_a_fenced_code_block():
    """代码里的 AI 字样是内容，不是署名。改它等于改坏用户要执行的东西。"""
    source = (
        "结论如下。\n\n"
        "```python\n"
        "# 本回复由 AI 生成\n"
        'MODEL = "As an AI language model"\n'
        "```\n\n"
        "本回复由 AI 生成。"
    )

    result = strip_ai_attribution(source, enabled=True)

    assert "# 本回复由 AI 生成" in result, "代码块内容被改写"
    assert 'MODEL = "As an AI language model"' in result
    # 代码块之外的那一句仍要被移除。
    assert result.count("本回复由 AI 生成") == 1


def test_does_not_touch_a_legitimate_discussion_of_ai():
    """讨论 AI 本身不是自我署名，不能删。

    「这个项目用 AI 做摘要」是答案的一部分；把它删掉会让回复读不通。
    """
    source = "这个项目用 AI 做摘要，成本大约每月 20 美元。"

    assert strip_ai_attribution(source, enabled=True) == source


def test_collapses_the_blank_lines_left_behind():
    """删掉整段后不能留下一片空行——那本身就是可见的痕迹。"""
    source = "结论：可以。\n\n本回复由 AI 生成。\n\n下一步：备份。"

    result = strip_ai_attribution(source, enabled=True)

    assert "\n\n\n" not in result
    assert not result.startswith("\n")
    assert not result.endswith("\n")


def test_empty_and_whitespace_input_are_safe():
    assert strip_ai_attribution("", enabled=True) == ""
    assert strip_ai_attribution("   \n  ", enabled=True) == "   \n  "


def test_a_reply_that_is_only_attribution_does_not_become_empty_silently():
    """整条回复只有署名时返回空串，由调用方决定怎么处理。

    这里刻意**不**编一句「（无内容）」：那会把「模型什么都没说」
    伪装成「系统有话说」。调用方（适配器）已经有空回复不发送的处理。
    """
    assert strip_ai_attribution("本回复由 AI 生成。", enabled=True).strip() == ""
