"""Removal of AI self-attribution sentences from a model reply.

需求 8 点名了 cc-switch 的「隐藏 AI 署名」。cc-switch 改的是
`attribution.commit` / `attribution.pr`——Claude Code 写 git commit 时的
`Co-Authored-By`。本项目不代写 commit，但同一个用户意图在聊天场景里有确切落点：
模型经常在回复里自报身份（「作为一个 AI 助手，我……」「本回复由 AI 生成」），
QQ / 企业微信这类面向真人的渠道里这类句子既占篇幅又暴露实现细节。

因此这里实现的是**语义等价物**而不是同名字段：一个供应商级开关，
打开后在该供应商返回的回复文本上移除 AI 自我署名，其余内容一字不动。

设计约束（每条都有对应用例，见 ``tests/llm/test_ai_attribution.py``）：

* **默认关闭。** 这是会改写模型输出的开关，默认改写等于替用户做决定。
* **只删署名，不删答案。** 「作为一个 AI，我建议你先备份」里
  「我建议你先备份」是答案；整句删掉就是丢答案。
* **不进代码块。** 代码里的 ``AI`` 字样是内容，改它等于改坏用户要执行的东西。
* **不碰对 AI 的正常讨论。** 「这个项目用 AI 做摘要」是答案的一部分。
  判定锚点是**第一人称自指**或**「本回复由…生成」这类出处声明**，
  而不是出现了 ``AI`` 这个词。
"""

from __future__ import annotations

import re

__all__ = ["strip_ai_attribution"]


#: 整句都是署名/免责声明的形态：直接整句删除。
#:
#: 每一条都要求句子**以**该模式开头并延续到句末，避免把包含这些词的正常句子
#: 当成署名。例如「这个项目用 AI 做摘要」不匹配——它的主语不是 AI 自身。
_STANDALONE_PATTERNS: tuple[re.Pattern[str], ...] = (
    # 「本回复由 AI 生成」「以上内容由人工智能生成，仅供参考」
    re.compile(
        r"^(?:本|该|此|以上)?\s*(?:回复|内容|答复|回答|文本|结果)?\s*"
        r"(?:由|系|为)\s*(?:AI|Ai|ai|人工智能|大模型|语言模型|机器人)"
        r"[^\n]*?(?:生成|撰写|提供|产生)[^\n]*$",
        re.IGNORECASE,
    ),
    # 「我是一个AI语言模型」「我只是一个人工智能」
    re.compile(
        r"^我(?:只)?(?:是|作为)\s*(?:一个|一名|一台)?\s*"
        r"(?:AI|Ai|ai|人工智能|大语言模型|语言模型|大模型|机器人)[^\n]*$",
        re.IGNORECASE,
    ),
    # "This response was generated by an AI assistant."
    re.compile(
        r"^(?:this|the)\s+(?:response|answer|reply|text|content)\b[^\n]*?"
        r"\bgenerated\b[^\n]*?\b(?:ai|artificial intelligence|language model)\b[^\n]*$",
        re.IGNORECASE,
    ),
    # "I am an AI language model." / "I'm just an AI."
    re.compile(
        r"^i(?:'m|\s+am)\s+(?:just\s+)?an?\s+"
        r"(?:ai|artificial intelligence|language model)\b[^\n]*$",
        re.IGNORECASE,
    ),
)

#: 只作为**前缀**出现的形态：删掉前缀，保留后面的答案。
#:
#: 中文前缀吃掉结尾的逗号或顿号；英文前缀吃掉逗号与随后的空格。
#: 后半句必须非空，否则交给上面的整句规则处理。
_PREFIX_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(
        r"^作为(?:一个|一名|一台)?\s*"
        r"(?:AI|Ai|ai|人工智能|大语言模型|语言模型|大模型)[^，,。\n]*[，,、]\s*",
        re.IGNORECASE,
    ),
    re.compile(
        r"^as\s+an?\s+(?:ai|artificial intelligence|language model)[^,\n]*,\s*",
        re.IGNORECASE,
    ),
)

_FENCE_PATTERN = re.compile(r"^\s*```")


def _strip_sentence(line: str) -> str:
    """Return the line with any AI self-attribution removed."""
    stripped = line.strip()
    if not stripped:
        return line
    for pattern in _STANDALONE_PATTERNS:
        if pattern.match(stripped):
            return ""
    for pattern in _PREFIX_PATTERNS:
        replaced = pattern.sub("", stripped, count=1)
        if replaced != stripped and replaced.strip():
            # 前缀删掉后首字母可能变成小写句中词，这里不做大小写修饰：
            # 猜测性地改写用户可见文本比留下一个小写开头更糟。
            return replaced.strip()
    return line


def _collapse_blank_runs(lines: list[str]) -> list[str]:
    """Drop the blank-line runs left behind by removed sentences.

    删掉整段之后留下一片空行本身就是可见的痕迹——「隐藏」没做到。
    """
    collapsed: list[str] = []
    for line in lines:
        if not line.strip() and collapsed and not collapsed[-1].strip():
            continue
        collapsed.append(line)
    while collapsed and not collapsed[0].strip():
        collapsed.pop(0)
    while collapsed and not collapsed[-1].strip():
        collapsed.pop()
    return collapsed


def strip_ai_attribution(text: str, *, enabled: bool) -> str:
    """Remove AI self-attribution sentences when the provider opts in.

    ``enabled`` 为假时**逐字符**返回原文：这是一个会改写模型输出的开关，
    默认不改写。围栏代码块内部完全跳过。整条回复只剩空白时返回空串，
    由调用方决定怎么处理——刻意不补一句「（无内容）」，那会把
    「模型什么都没说」伪装成「系统有话说」。
    """
    if not enabled or not text or not text.strip():
        return text

    lines = text.split("\n")
    result: list[str] = []
    in_code = False
    for line in lines:
        if _FENCE_PATTERN.match(line):
            in_code = not in_code
            result.append(line)
            continue
        if in_code:
            result.append(line)
            continue
        result.append(_strip_sentence(line))

    return "\n".join(_collapse_blank_runs(result))
